import React from 'react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export const TermsAndConditions = () => {
  return (
    <section className='h-auto w-screen Poppins flex flex-col items-center bg-[#fafae0]'>
      <Navbar />
      <section className='w-[80%] mt-[9%] p-7 bg-white rounded-xl border-2 border-accentYellow'>
        <h1 className='text-2xl font-semibold mb-4 text-center'>TERMS AND CONDITIONS</h1>
        <p className='pb-2'>Instaport delivery. If you continue to browse and use our app/website you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern SmartShift Logistics Solutions Private Limited's (Owner of Instaport delivery) relationship with Welcome you in relation to this app/website and the Services (as described below)</p>
        <p className='pb-2'>In the event there is a conflict between the terms and conditions specified herein and the provisions of any other document executed between the to parties hereto, the terms and conditions specified herein would prevail.</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>DEFINITIONS</h1>
        <p className='pb-2'>The following definitions apply to the terms and conditions set out below that govern this contract of Carriage between you and us:</p>
        <ul>
          <li>•	"We", "us", "our", "Carrier", "Instaport delivery", "Company" shall refer to SmartShift Logistics Solutions Private Limited (owner of Instaport delivery), its employees, authorised agents and its independent contractors and the entities that carry or undertake to carry the consignment hereunder or perform any other services incidental thereto on its behalf.</li>
          <li>•	“You”, “your”, “consignor” shall refer to the sender, consignor or consignee of the Consignment, holder of this Consignment Note, receiver and owner of the contents of the Consignment or any other party having a legal interest in those contents, as the case may be.</li>
          <li>•	“Services” means the technology-based services provided by Instaport delivery which enable the following:
            <ul>
              <li>o	the hiring of vehicles by Customers for a point to point service, or for time and usage based service within city limits and outside the city limits, including inter-city all over India, through the internet and / or mobile telecommunications devices;</li>
              <li>o	hiring of labour by Customers for loading/unloading of the consignment; and</li>
              <li>o	such other services which Instaport delivery may from time to time add.</li>
              <li>o	"Carriage" means and includes the whole of the operations and services undertaken by us in connection with the Consignment. </li>
              <li>o	"Consignment" means any package, parcel, sachet, or freight which is or are given to and accepted by us for carriage under our Consignment Note.</li>
              <li>o	“Dangerous Goods” means goods classified as dangerous as per ICAO T.I., IATA DGR, IMDG-Code, ADR or other national regulations for transport.</li>
              <li>o	“Delivery” means the tender of the consignment to the consignee or intimation about the arrival of the consignment.</li>
              <li>o	"Prohibited Items" means any goods or materials, the Carriage of which is prohibited by Applicable Law.</li>
              <li>o	“Receiver” or “Consignee” shall refer to the recipient or addressee or the consignee of the Consignment.</li>
              <li>o	“Applicable Law” means all laws, statutes, ordinance, regulations, guidelines, policies, rules, bye-laws, notifications, directions, directives and orders or other governmental restrictions or any similar form of decision of, or determination by, or any interpretation, administration and other pronouncements having the effect of law of the Republic of India or any other applicable jurisdiction by state, municipality, court, tribunal, government, ministry, department, commission, arbitrator or board or such other body which has the force of law in India.</li>
            </ul>
          </li>
        </ul>
        <h1 className='text-xl font-semibold mt-4 self-start'>USER(S) ELIGIBILITY</h1>
        <p className='pb-2'>User(s) means any individual or business entity/ organization that legally operates in India or in other country, uses and has the right to use the Services provided by Instaport delivery. It is hereby being clarified that our Services are available only to those individuals or business entities/organizations who can form legally binding contracts under the Applicable Law. To be a User(s) and be eligible to use our Services, an individual must be at least 18 (eighteen) years of age. Instaport delivery advises its users that while accessing the web site, they must follow/abide by the related laws. Instaport delivery is not responsible for the possible consequences caused by your behavior / acts during use of web site. Instaport delivery may, in its sole discretion, refuse the service to anyone at any time.</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>USER(S) AGREEMENT</h1>
        <p className='pb-2'>This agreement applies to user(s) if user(s) are visitors, registered - free or paid user(s) who access the web site for any purpose. It also applies to any legal entity which may be represented by you under actual or apparent authority. User(s) may use this site solely for their own personal or internal purposes.</p>
        <p className='pb-2'>This agreement applies to all Instaport delivery Services offered on the web site, collectively with any additional terms and condition that may be applicable to the specific service used/accessed by user(s).In the event of a conflict or inconsistency between any provision of the terms and conditions mentioned herein with those of the particular service, the provisions of the terms and conditions applicable to such specific Services shall prevail.</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>AMENDMENT TO USER(S) AGREEMENT</h1>
        <p className='pb-2'>Instaport delivery may change, modify, amend, or update this agreement from time to time with or without any prior notification to user(s) and the amended and restated terms and conditions of use shall be effective immediately on posting. If you do not adhere to the changes, you must stop using the service. Your continuous use of the Services will signify your acceptance of the changed terms and deemed acceptance of the amended Agreement. Further, User(s) shall also be bound by any amendment made in any policy or agreement from time to time, referred to in these Terms of Service.</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>INTELLECTUAL PROPERTY RIGHTS</h1>
        <p className='pb-2'>Instaport delivery is the sole owner or lawful licensee of all the rights to the web site and its content. Web site content means its design, layout, text, images, graphics, sound, video etc. The web site content embody trade secrets and intellectual property rights protected under worldwide copyright and other laws. All title, ownership and intellectual property rights in the web site and its content shall remain with Instaport delivery, its affiliates or licensor's of Instaport delivery content, as the case may be.</p>
        <p className='pb-2'>All rights, not otherwise claimed under this agreement or by Instaport delivery.in, are hereby reserved. The information contained in this web site is intended, solely to provide general information for the personal use of the reader, who accepts full responsibility for its use. Instaport delivery does not represent or endorse the accuracy or reliability of any information, or advertisements (collectively, the "content") contained on, distributed through, or linked, downloaded or accessed from any of the Services contained on this web site, or the quality of any products, information or other materials displayed, or obtained by you as a result of an advertisement or any other information or offer in or in connection with the Service. We accept no responsibility for any errors or omissions, or for the results obtained from the use of this information. All information in this web site is provided "AS IS " with no guarantee of completeness, accuracy, timeliness or of the results obtained from the use of this information, and without warranty of any kind, express or implied, including, but not limited to warranties of performance, merchantability and fitness for a particular purpose. Nothing herein shall to any extent substitute for the independent investigations and the sound technical and business judgment of the user(s). In no event shall Instaport delivery be liable for any direct, indirect, incidental, punitive, or consequential damages of any kind whatsoever with respect to the Service. User(s) of this site must hereby acknowledge that any reliance upon any content shall be at their sole risk.</p>
        <p className='pb-2'>Instaport delivery reserves the right, in its sole discretion and without any obligation, to make improvements to, or correct any error or omissions in any portion of the Service or the app/website. Trademark</p>
        <p className='pb-2'>All related icons and logos are registered trademarks or trademarks or service marks of Instaport delivery in various jurisdictions and are protected under applicable copyright, trademark and other proprietary rights laws. The unauthorized copying, modification, use or publication of these marks is strictly prohibited. Copyright</p>
        <p className='pb-2'>All content on this web site is the copyright of Instaport delivery except the third party content and link to third party web sites on our app/website.</p>
        <p className='pb-2'>Systematic retrieval of Instaport delivery content to create or compile, directly or indirectly, a collection, compilation, database or directory (whether through robots, spiders, automatic devices or manual processes) without written permission from Instaport delivery is prohibited.</p>
        <p className='pb-2'>In addition, use of the content for any purpose not expressly permitted in this Agreement is prohibited and may invite legal action. As a condition of your access to and use of Instaport delivery's Services, you agree that you will not use the web site service to infringe the intellectual property rights of Instaport delivery or any other third party in any way. Instaport delivery reserves the right to terminate the account of a user(s) upon any infringement of the rights of any third party in conjunction with use of the Instaport delivery service, or if Instaport delivery believes that user(s) conduct is harmful to the interests of Instaport delivery, its affiliates, or other users, or for any other reason in Instaport delivery's sole discretion, with or without cause. You shall be liable to indemnify Instaport delivery for any losses or expenses incurred by Instaport delivery due to any infringement of intellectual property rights owned by Instaport delivery without prejudicing Instaport delivery's right to bring any legal action against you.</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>LINKS TO THIRD PARTY SITES</h1>
        <p className='pb-2'>Links to third party sites are provided by web site as a convenience to user(s) and Instaport delivery has no control over such sites i.e content and resources provided by them.</p>
        <p className='pb-2'>Instaport delivery may allow user(s) access to content, products or Services offered by third parties through hyperlinks (in the form of word link, banners, channels or otherwise) to such Third Party's web site. You are cautioned to read such sites' terms and conditions and/or privacy policies before using such sites in order to be aware of the terms and conditions of your use of such sites. Instaport delivery believes that user(s) acknowledge that Instaport delivery has no control over such third party's site, does not monitor such sites, and Instaport delivery shall not be responsible or liable to anyone for such third party site, or any content, products or Services made available on such a site. User(s) shall review Instaport delivery's Privacy Policy and abide by Instaport delivery's Privacy Policy at the time of the User(s) interaction with Instaport delivery, with respect to and concerning any information and data.</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>TERMINATION</h1>
        <p className='pb-2'>Most content and some of the features on the web site are made available to visitors free of charge. However, Instaport delivery reserves the right to terminate access to certain areas or features of the web site at any time for any reason, with or without notice. Instaport delivery also reserves the universal right to deny access to particular users to any/all of its Services without any prior notice/explanation in order to protect the interests of Instaport delivery and/or other visitors to the web site. Instaport delivery reserves the right to limit, deny or create different access to the web site and its features with respect to different user(s), or to change any of the features or introduce new features without prior notice.</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>TERMS & CONDITIONS FOR USE OF OUR SERVICE</h1>
        <p className='pb-2'>The following Terms & Conditions shall apply to customers utilising the Services offered by the Company for the hiring of vehicles: The customer shall pay the fare (as agreed), parking charges, additional night surcharge (where applicable) and any fee or levy presently payable or hereinafter imposed by the Applicable Law or required to be paid for availing the Services of Instaport delivery. The customer agrees and accepts that the use of the Services provided by the Company is at the sole risk of the Customer, and further acknowledges that the Company disclaims all representations and warranties of any kind, whether express or implied. The customer shall ensure that he/she will not indulge in any of the following activities while availing the service:</p>
        <ul>
          <li>Soiling or damaging the body and/or any other interiors of the vehicles.</li>
          <li>Misusing, soiling or damaging any of the devices (technical/non-technical) in the vehicle.</li>
          <li>Asking the driver to break any Traffic/RTO/City Police and/or government rules for any purpose. The driver has the right to refuse such a request by the customer. The driver also has the right to refuse such a pick-up.</li>
          <li>Pressurizing the driver to overload truck with the consignment than the allowed limit.</li>
        </ul>
        <p className='pb-2'>The Customer shall indemnify Company from and against and in respect of any or all liabilities, losses, charges and expenses (including legal fees and costs on a full indemnity basis) claims, demands, actions and proceedings which Company may incur or sustain directly or indirectly from or by any reason of or in relation to the use or proposed use of the Services by the Customer and shall pay such sums on demand on the Company.</p>
        <p className='pb-2'>The Company is hereby authorized to use the location based information provided by any of the telecommunication companies when the Customer uses the mobile phone to make a vehicle booking. The location based information will be used only to facilitate and improve the probability of locating a mini-truck for the Customer.</p>
        <p className='pb-2'>The Company shall be entitled to disclose to all companies within its group, or any government body as so required by the Applicable Law or by directive or request from any government body, the particulars of the Customer in the possession of Company in any way as Company, in its absolute discretion, deems fit or if it considers it in its interests to do so.</p>
        <p className='pb-2'>The Company shall be entitled at any time without giving any reason to terminate the booking of the vehicle done by the Customer. User(s) shall indemnify Instaport delivery with respect to any expenses incurred with respect to such booking.</p>
        <p className='pb-2'>In case of lost items during the transit, Company will try to locate the items on a "best-effort" basis but is not responsible for the same in case of loss or damage or theft or misappropriation to / of the same. Instaport delivery aggregates the vehicles for the purposes of providing Services. In the event of loss of any item, User(s) shall not have any right to withhold the payment to be made to Instaport delivery. Further, in the event any payments from the User to Instaport delivery are pending for the period prescribed by Instaport delivery in its respective invoice / statement, Instaport delivery reserves the right, in accordance with the Applicable Law, to exercise particular lien over the consignment till full payment is made to Instaport delivery for the Services. Additionally, User(s) will be liable to indemnify Instaport delivery against any loss, damage or expenses incurred by it due to the custody of the consignment during this period.</p>
        <p className='pb-2'>Any complaint in respect of the Services or the use of the vehicles, the Customer has to inform the Company of the same in writing within 24 hours of using the vehicles or Services of the Company.</p>
        <p className='pb-2'>The Company shall not be liable for any conduct of the drivers of the vehicles. However, the Company encourages you to notify it, of any complaints that you may have against the driver that you may have hired using the Company's Services.</p>
        <p className='pb-2'>The Company shall be entitled to add to, vary or amend any or all these terms and conditions at any time and the Customer shall be bound by such addition, variation or amendment once such addition, variation or amendment are incorporated into these terms and conditions at Company's website at www.instaport delivery.in on the date that Company may indicate that such addition, variation or amendment is to come into effect.</p>
        <p className='pb-2'>All the calls made to the Company's call centre are recorded by the Company for quality and training purposes. In the event you place a query on our app/website including any query with respect to our Services, applicable fees or Terms of Service, you hereby expressly agree to consent to receive our responses, whether by way of telephonic calls or electronic mail, to such query and all related information with respect to our Services. For removal of doubts, related information shall include without limitation any marketing and/or commercial information. You understand, agree and acknowledge that such information shall in no event, qualify as unsolicited commercial communication under the Telecom Unsolicited Commercial Communications Regulations, 2007 and/or due to disclosure of such information, our telephone numbers shall not qualify to be registered under the 'National Do Not Call Register' or the 'Private Do Not Call Register' in accordance with the Telecom Unsolicited Commercial Communications Regulations, 2007 or any other Applicable Law.</p>
        <p className='pb-2'>Cancellation Policy: All cancellations made 5 minutes after driver allocation will incur a cancellation fee of INR. 50/- (Indian Rupees Fifty only). Cancelling four bookings in a day after driver allocation will temporarily suspend your account for 24 hours. Figures are subject to change.</p>
        <p className='pb-2'>Toll Charges: In case of a toll on your trip, return toll fare will be charged.</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>LABOUR SERVICES</h1>
        <p className='pb-2'>Instaport delivery provides the option to Customers to utilize Labour Services by clicking on the “Include Labour” toggle on the review screen of the website/App.</p>
        <p className='pb-2'>“Labour Services” means that the service provided by the labour wherein labour undertakes the task of loading/unloading the consignment of goods from the loading/unloading point to the vehicle or vice-versa, as the case may be.</p>
        <p className='pb-2'>“Labour” means the driver of the vehicle and the person accompanying him in the vehicle.</p>
        <p className='pb-2'>By clicking on the “Include Labour” toggle on the review screen of the Website/App or by availing the Labour Services, the Customer agrees to the following terms and conditions. These terms shall be applicable in addition to the terms and conditions applicable to the customers for hiring of vehicles:</p>
        <ul>
          <li>You acknowledge that the Labour Service is provided only for ground floor to ground floor loading/unloading. You acknowledge that the ground floor movement (distance between the transport vehicle and the loading/unloading point) shall not exceed 25 metres.</li>
          <li>You acknowledge that the extra charges (as visible in the Invoice) for the Labour Service shall be payable by you.</li>
          <li>You agree that you shall be present in person at the time of loading/unloading of Consignment. If you are not available, an authorised representative must be present.</li>
          <li>You agree that Instaport delivery shall not be liable for misbehaviour of the labour during the loading/unloading. However, you are requested to bring to the notice of Company such incidents. The Company, in its sole discretion, may take action in such matters.</li>
        </ul>
        <h1 className='text-xl font-semibold mt-4 self-start'>CONFIDENTIALITY</h1>
        <p className='pb-2'>User(s) shall not disclose any information received under the contract of service with Instaport delivery to any third party. Access to any information which pertains to business of Instaport delivery shall be kept confidential to the extent it might adversely impact Instaport delivery's business. User(s) shall be liable to indemnify Instaport delivery against any loss of business or reputation due to the act of the user(s).</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>DISCLAIMER</h1>
        <p className='pb-2'>All vehicles registered with the Company are continuously tracked using mobile technology for security reasons only. It is hereby made expressly clear to you that the Company does not own any vehicle nor it directly or indirectly employ any driver for the vehicles or Labour for loading/unloading of Consignment. Vehicles, drivers and Labour are all supplied by third parties and the Company disclaims any and all liability(ies) in respect of the Labour, drivers and the vehicles alike.</p>
        <p className='pb-2'>The Company have right to use the customer contact information for its own marketing purposes. The Company may send regular SMS updates to the mobile numbers registered with it.</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>ACE PLUS TERMS AND CONDITIONS</h1>
        <ul>
          <li>Only ground floor to ground floor loading/unloading is allowed</li>
          <li>Distance between Instaport delivery truck and loading/unloading point should not be more than 25 feet (8 metres).</li>
          <li>Max weight per box allowed is 25 kg and upto 30 such boxes/cartons are allowed.</li>
          <li>Labour charge will be automatically added to the invoice.
          </li>
        </ul>
        <h1 className='text-xl font-semibold mt-4 self-start'>YOUR ACCEPTANCE OF OUR TERMS AND CONDITIONS</h1>
        <p className='pb-2'>By giving us your consignment you accept our terms and conditions set out in the consignment note and/or the contract of carriage and/or the contract for the performance of other services on behalf of yourself and/or anyone else who has an interest in the consignment or the performance of other Services irrespective of whether you have signed the front of our consignment note or not. Our terms and conditions also cover and can be invoked by anyone we use or sub-contract to collect, transport, deliver your consignment or perform other Services as well as our employees, directors and agents. Only one of our authorised officers may agree to a variation of these terms and conditions in writing. When you give us the consignment with oral or written instructions that conflict with our terms and conditions we shall not be bound by such instructions.</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>YOUR OBLIGATIONS</h1>
        <ul>
          <li>•	You warrant, undertake and guarantee to us:
            <ul>
              <li>o	The contents of the consignment (including but not limited to weight and number of items) have been properly described on our consignment note and that the Consignment Note is complete in all respects and the documents as required for the transporting the consignment including invoice, permits are enclosed with the Consignment Note.</li>
              <li>o	That the contents of the Consignment are not Prohibited Items and/or are not restricted by the applicable regulations and that you will supply to us any Dangerous Goods declaration that is needed, properly and accurately in accordance with Applicable Law and neither you nor the consignee is a person or organisation with whom we or you may not legally trade under Applicable Law.</li>
              <li>o	That all statements and information and documents provided by you relating to the Consignment will be true and correct and you acknowledge that in the event that you make untrue or fraudulent statement about the Consignment or any of its contents, you would risk a civil claim and/or criminal prosecution the penalties for which may include forfeiture and sale. You agree to indemnify us and hold us harmless from any claims that may be brought against us or our agents arising from the information provided by you.</li>
              <li>o	We are authorised to deliver the goods at the address mentioned on the Consignment Note and without prejudice to the foregoing it is expressly agreed that we shall be conclusively presumed to have delivered the goods in accordance with this contract. We will be sending the delivery confirmation by SMS/e-mails, no-response within 24 hours would be considered as an affirmative to the delivery.</li>
              <li>o	You have declared the correct weight of the consignment and you will provide any special equipment we may need to load or unload the consignment on or off our vehicles.</li>
              <li>o	When you have asked us to charge the receiver or a third party and the receiver or third party does not pay us you will promptly settle our invoice together with an administration fee in full within 7 days of us sending you the invoice</li>
              <li>o	Applicable Law has been complied with by you.</li>
            </ul>
          </li>
          <li>•	You understand, agree and acknowledge that the Services are not suitable for transportation of valuables like cash, gold, silver, diamond, precious stones, jewels or jewellery, expensive luxury items etc. (“Valuables”). If you handover / load the vehicles with Valuables for transportation, any loss / damage / theft / misappropriation to / of the consignment shall be at your risk and not ours, for the reasons mentioned earlier and without prejudice, we shall not only have the right to explicitly and specifically disclaim any liability and/or responsibility arising/accruing from the damage / loss / theft / misappropriation to/of the consignment or any contents of the consignment, but also the right to claim indemnification from you where we have suffered loss of reputation / goodwill due to your actions of breaching our terms of service.</li>
          <li>•	You understand, agree and acknowledge that if the consignment or any contents thereof are of the value exceeding INR 25,000/- (Indian Rupees Twenty-Five Thousand only), you shall get the consignment insured from a General Insurance company operating in India before handing over the consignment for transportation. In absence of adequate insurance to cover loss of goods in transit or in absence of wrong or non-declaration of the consignment details / value, and whether insured or not, the transportation of the consignment shall be entirely at your risk and not ours and we explicitly and specifically disclaim any liability and/or responsibility arising/accruing from the damage / loss / theft / misappropriation or any insurable loss to / of the consignment or any contents of the consignment and you further agree to indemnify us in all those cases where we have suffered loss of reputation / goodwill due to your actions of breaching our terms of service.</li>
          <li>•	You agree to indemnify us and hold us harmless from any liabilities we may suffer or any costs, damages or expenses, including legal costs, we incur either to you or to anyone else arising out of you being in breach of any of these warranties, representations and guarantees, even if we inadvertently accept a consignment that contravenes any of your obligations.</li>
          <li>•	You certify that all statements and information you provide relating to the transportation of the consignment will be true and correct. You acknowledge that in the event that you make untrue or fraudulent statements about the consignment or any of its contents you risk a civil claim and/or criminal prosecution the penalties for which include forfeiture and sale of your consignment. To the extent that we may voluntarily assist you in completing the required customs and other formalities such assistance will be rendered at your sole risk. You agree to indemnify us and hold us harmless from any claims that may be brought against us arising from the information you provide to us and any costs we will incur regarding this, and pay any administration fee we may charge you for providing the Services described in this condition.</li>
          <li>•	The customer agrees and acknowledges that the use of the Services offered by Company is at the sole risk of the customer and that Company disclaims all representations and warranties of any kind, whether express or implied as to condition, suitability, quality, merchantability and fitness for any purposes are excluded to the fullest extent permitted by Applicable Law. Without prejudice to the above, the Company makes no representation or warranties with respect to:
            <ul>
              <li>o	The Services meeting the customer's requirements.</li>
              <li>o	The Services will be uninterrupted, timely, secure, or error-free.</li>
              <li>o	Any responsibility or liability for any loss or damage, howsoever caused or suffered by the Customer arising out of the use of Services offered by Company or due to the failure of Company to provide Services to the Customer for any reason whatsoever including but not limited to the Customer's non-compliance with the Services' recorded voice instructions, malfunction, partial or total failure of any network terminal, data processing system, computer tele-transmission or telecommunications system or other circumstances whether or not beyond the control of Company or any person or any organization involved in the above mentioned systems.</li>
              <li>o	Any liability for any damages of any kind arising from the use of the Service offered by the Company, including, but not limited to direct, indirect, incidental, punitive, and consequential damages.</li>
              <li>o	Any additional or extra charges for far off locations & toll charges as well.</li>
            </ul>
          </li>
          <li>•	Applicable Law has been complied with by you.
            <ul>
              <li>o	Circumstances beyond our control such as (but not limited to):
                <ul>
                  <li>	Acts of god including earthquakes, cyclones, storms, flooding, fire, disease, fog, snow or frost or other natural calamities or disasters</li>
                  <li>	Force majeure including (but not limited to) war, epidemics, pandemics, accidents, acts of public enemies, strikes, embargoes, perils of the air, local disputes or civil commotions.</li>
                  <li>	National or local disruptions in air or ground transportation networks and mechanical problems to modes of transport or machinery.</li>
                  <li>	Latent defects or inherent vice in the contents of the consignment.</li>
                  <li>	Criminal acts of third parties such as theft and arson.</li>
                </ul>
              </li>
              <li>o	Your acts or omissions or those of third parties such as:
                <ul>
                  <li>You being in breach of (or any other party claiming an interest in the consignment causing you to breach) your obligations under these terms and conditions.</li>
                </ul>
              </li>
              <li>The contents of the consignment consisting of any article that is a prohibited item / Dangerous Goods / Valuables even though we may have accepted the consignment by mistake or you have willingly handed it over to us without notifying / informing / declaring to us.</li>
            </ul>
          </li>
        </ul>
        <h1 className='text-xl font-semibold mt-4 self-start'>DANGEROUS GOODS / SECURITY</h1>
        <ul>
          <li>Dangerous Goods
            <ul>
              <li>We do not carry, nor perform other Services regarding, goods which are in our sole opinion Dangerous Goods including, but not limited to, those specified in the regulations, guidelines, technical instructions, codes applicable to us and our business or to the transport of, or the performance of other Services regarding, Dangerous Goods.</li>
              <li>We may at our discretion accept some Dangerous Goods for carriage, or for the performance of other Services, in some locations if you have been accorded the status of an approved customer and this must be given by us in writing before your consignment can be accepted. Your Dangerous Goods will only be accepted if they comply with the applicable regulations and our requirements. Details of our requirements together with the procedure for applying for approved customer status are available from our nearest office and a dangerous goods surcharge will be invoiced to you upon acceptance of your consignment.</li>
            </ul>
          </li>
          <li>•	Prohibited Items: We do not accept consignments that contain prohibited items.</li>
          <li>•	We accept consignments only upon your declaration of the type and value of the consignment (“said to contain” basis). We have no responsibility whatsoever as to the correctness of description, type or value thereof and you agree to indemnify us and hold us harmless from any claims that may be brought against us arising out of or relating to such declaration provided by you and any costs we will incur relating thereto.</li>
        </ul>
        <h1 className='text-xl font-semibold mt-4 self-start'>REJECTED CONSIGNMENTS</h1>
        <p className='pb-2'>If the receiver refuses to accept delivery, we will try to contact you and agree to the next action if it is appropriate. You agree to pay us any costs we incur in forwarding, disposing of or returning the consignment and our charges (if any) for the agreed appropriate next action.</p>
        <p className='pb-2'>If user(s) terminates the agreement with Instaport delivery with respect to any consignment, user(s) shall be liable to pay Instaport delivery the entire fees and other expenses so incurred with respect to such consignment.</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>CLAIMS BROUGHT BY THIRD PARTIES</h1>
        <p className='pb-2'>You undertake to us that you shall not permit any other person who has an interest in the consignment to bring a claim or action against us arising out of Carriage even though we may have been negligent or in default and if a claim or action is made you will indemnify us against the consequences of the claim or action and the costs and expenses we incur in defending it.</p>
        <p className='pb-2'>The above mentioned terms and conditions of use and/or Agreement and the Privacy Policy constitute the entire agreement between the User(s) and Instaport delivery with respect to access to and use of the web site and the Services offered by Instaport delivery, superseding any prior written or oral agreements in relation to the same subject matter herein.</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>INSTAPORT DELIVERY REFERRAL PROGRAM</h1>
        <p className='pb-2'>Please find all referral related terms and conditions [here](https://instaport delivery.in/referral-tnc)</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>ASSURED BOOKING TERMS</h1>
        <ul>
          <li>•	Only the users who have received the communication are eligible under this scheme.</li>
          <li>•	This scheme is eligible for Tata Ace open category bookings between 10:30-19:00 Hours only.</li>
          <li>•	This scheme is eligible when the pickup location is from Perambur, Choolai, Vyasarpadi, Purshwalkam, Ayanavram and Kilpauk clusters in Chennai only.</li>
          <li>•	Each user will only be eligible once a day for this scheme i.e. a user will be eligible for a maximum of Rs 50/- (Rupees Fifty only) cashback in a day in case of unfulfilled booking.</li>
          <li>•	The cashback will be auto credited in user's account within 24 hours of an unfulfilled booking.</li>
          <li>•	Management decision will be considered final with regard to all aspects of the scheme.</li>
        </ul>
        <h1 className='text-xl font-semibold mt-4 self-start'>GOVERNING LAW AND JURISDICTION</h1>
        <p className='pb-2'>These Terms of Service shall be governed by and construed in accordance with the laws of the India, without regard to the principles of conflict of laws. The courts of [Bengaluru] shall have exclusive jurisdiction over any disputes, differences or claims arising out of or in connection with these Terms of Service or any Services provided by us pursuant to these Terms of Service</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>GRIEVANCE OFFICER</h1>
        <p className='pb-2'>In accordance the Consumer Protection (E-Commerce) Rules, 2020, the name and contact details of the Nodal/Grievance Officer are provided, any grievances under the said Rules, may have relevance with respect to the said Rules, its treatment or any grievance related to Services being availed at INSTAPORT DELIVERY, the request may be directed by the Authority under the said Rules, to such grievance officer or at the below mentioned coordinate:</p>
        <h1 className='text-xl font-semibold mt-4 self-start'>DISCLAIMER</h1>
        <p className='pb-2'>The information contained in this website and Instaport delivery App is for general information purposes only. The information is provided by Instaport delivery and while we endeavor to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website / App or the information, products, services, or related graphics contained on the website / App for any purpose. Any reliance you place on such information is therefore strictly at your own risk.</p>
        <p className='pb-2'>In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website / App.</p>
        <p className='pb-2'>Through this website / App you are able to link to other websites which are not under the control of Instaport delivery. We have no control over the nature, content and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.</p>
        <p className='pb-2'>Every effort is made to keep the portal up and running smoothly. However, Instaport delivery takes no responsibility for, and will not be liable for, the portal being temporarily unavailable due to technical issues beyond our control.</p>
      </section>
      <Footer />
    </section>
  )
}
